## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

julia:
  - 1.1

os:
  - linux
  - osx

after_success:
  - julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
